ansiColor('xterm') {
  node {
    stage('Checkout') {
      // clean the workspace
      cleanWs()
      // get some code from a GitHub repository
      checkout scm
    }
    stage('Setup') {
      sh "ansible-galaxy install -r requirements.yml"
    }
    stage('Validate') {
      sh "packer validate jenkins.json"
    }
    stage('Build') {
      withCredentials([usernamePassword(credentialsId: 'aws_access_keys', usernameVariable: 'AWS_ACCESS_KEY', passwordVariable: 'AWS_SECRET_KEY')]) {
        // run the packer build
        sh "packer build -var 'aws_region=us-west-2' jenkins.json"
      }
    }
    stage('Store Artifacts') {
      archiveArtifacts 'manifest.json'
    }
  }
}
